apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generator
  namespace: default
  labels:
    app: video-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "video-generator"
  template:
    metadata:
      labels:
        app: video-generator
    spec:
      containers:
      - name: video-generator
        image: $IMAGE_NAME
        env:
        - name: SPREADSHEET_ID
          value: $SPREADSHEET_ID
        - name: BUCKET_NAME
          value: $BUCKET_NAME
