steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cloud_build.sh
  env:
    - 'FRONTEND_CLIENT_ID=${_FRONTEND_CLIENT_ID}'
    - 'FRONTEND_API_KEY=${_FRONTEND_API_KEY}'