runtime: python37

handlers:
- url: /(.+)
  static_files: dist/pva-frontend/\1
  upload: dist/pva-frontend/.*

- url: /
  static_files: dist/pva-frontend/index.html
  upload: dist/pva-frontend/index.html

