runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : '1'
