runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.+)
  static_files: dist/pva-frontend/\1
  upload: dist/pva-frontend/.*

- url: /
  static_files: dist/pva-frontend/index.html
  upload: dist/pva-frontend/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
